export const AUTH_ACTION_SIGN_UP = "AUTH_ACTION_SIGN_UP";
export const AUTH_ACTION_SIGN_IN = "AUTH_ACTION_SIGN_IN";
export const AUTH_ACTION_AUTO_SIGN_IN = "AUTH_ACTION_AUTO_SIGN_IN";
export const AUTH_ACTION_SIGN_OUT = "AUTH_ACTION_SIGN_OUT";
export const AUTH_ACTION_PENDING = "AUTH_ACTION_PENDING";
export const AUTH_ACTION_ERROR = "AUTH_ACTION_ERROR";
export const AUTH_ACTION_REMOVE_ERROR = "AUTH_ACTION_REMOVE_ERROR";